-- 문제: 오프라인/온라인 판매 데이터 통합하기
-- 출처: [프로그래머스] SQL kit - SELECT
-- 난이도: Level 4
-- 포인트: UNION ALL
-- 날짜: 2025-11-11

-- 리팩토링 포인트:
--  1) UNION -> UNION ALL (중복 제거 불필요, 성능/정확성)
--  2) YEAR()/MONTH() -> 범위 조건으로 인덱스 활용
--      WHERE SALES_DATE >= '2022-03-01' AND SALES_DATE < '2022-04-01'과 같이. 기존 코드는 인덱스 비우호적...

SELECT DATE_FORMAT(SALES_DATE, '%Y-%m-%d') AS SALES_DATE,
    PRODUCT_ID,
    USER_ID,
    SALES_AMOUNT
FROM ONLINE_SALE
WHERE YEAR(SALES_DATE) = 2022
    AND MONTH(SALES_DATE) = 3
UNION
SELECT DATE_FORMAT(SALES_DATE, '%Y-%m-%d') AS SALES_DATE,
    PRODUCT_ID,
    NULL AS USER_ID,
    SALES_AMOUNT
FROM OFFLINE_SALE
WHERE YEAR(SALES_DATE) = 2022
    AND MONTH(SALES_DATE) = 3
ORDER BY SALES_DATE ASC,
    PRODUCT_ID ASC,
    USER_ID ASC;

/* 태초의 코드
 -- JOIN 써야하는 줄 알았다. 바보!
 
 SELECT
 DATE_FORMAT(SALES_DATE, '%Y-%m-%d') AS SALES_DATE,
 PRODUCT_ID,
 n.USER_ID,
 SALES_AMOUNT
 FROM ONLINE_SALE AS n
 RIGHT JOIN OFFLINE_SALE AS f
 ON n.SALES_DATE = f.SALES_DATE
 WHERE YEAR(SALES_DATE) = '2022' AND MONTH(SALES_DATE) = '03'
 ORDER BY SALES_DATE ASC, PRODUCT_ID ASC, USER_ID ASC;
 */