/*
📅 Date: 2025-11-14
🧩 Topic: DISTINCT
🐰 문제1 요약:
    - CATEGORY별로 BOOK_TITLE의 고유 개수를 COUNT(DISTINCT ...)로 계산하고 고유 책 제목 수가 2개 이상인 장르만 HAVING으로 필터링하는 문제.
*/

SELECT
    CATEGORY,
    COUNT(DISTINCT BOOK_TITLE) AS TITLE_COUNT
FROM LIBRARY_LOG
GROUP BY CATEGORY
HAVING TITLE_COUNT >= 2
ORDER BY CATEGORY;


/*
🐰 문제2 요약:
    - BOOK과 BORROW_LOG를 JOIN하여 CATEGORY별로
대출된 서로 다른 책 제목 수를 계산하는 문제.
*/

SELECT
    b.CATEGORY,
    COUNT(DISTINCT b.TITLE) AS TITLE_COUNT
FROM BOOK AS b
JOIN BORROW_LOG AS l
  ON b.BOOK_ID = l.BOOK_ID
GROUP BY b.CATEGORY
HAVING CATEGORY LIKE 'Lit%'
   AND TITLE_COUNT >= 1
ORDER BY b.CATEGORY ASC;