/*
📅 Date: 2025-12-17
🧩 Topic: UNION / INTERSECT / EXCEPT + ROUND
🐰 문제 요약 :
    - 두 판매 채널의 매출 데이터를 비교하여 특정 조건을 만족하는 상품 목록을 집합 연산으로 추출한다
*/

SELECT
    PRODUCT_ID
FROM ONLINE_SALE
WHERE ROUND((PRICE * QUANTITY)::numeric 1000, 2)

UNION

SELECT
    PRODUCT_ID
FROM OFFLINE_SALE
WHERE ROUND((PRICE * QUANTITY)::numeric 1000, 2)

INTERSECT
SELECT PRODUCT_ID
FROM ONLINE_SALE
INTERSECT
SELECT PRODUCT_ID
FROM OFFLINE_SALE
GROUP BY PRODUCT_ID;