/*
📅 Date: 2025-12-06
🧩 Topic: Multi LEFT JOIN (3 tables)
🐰 문제 요약 :
    - VIP 고객(Gold/Platinum)만 조회, 호텔 숙박비 + 식당 결제비 모두 포함해야 함
    - 반드시 LEFT JOIN 포함, 반드시 GROUP BY + COALESCE + 다중 JOIN, 고객별 집계 결과 출력
    
💡 리팩토링 포인트:
*/

SELECT
    g.NAME AS GUEST_NAME,
    g.LEVEL AS LEVEL,
    COUNT(DISTINCT b.BOOKING_ID) AS STAY_COUNT,
    COUNT(DISTINCT p.PAY_ID) AS MEAL_COUNT,
    SUM(b.ROOM_FEE) + SUM(p.BASE_FEE + COALESCE(p.EXTRA_FEE, 0)) AS TOTAL_SPENT
FROM HOTEL_GUEST AS g
INNER JOIN ROOM_BOOKING AS b ON g.GUEST_ID = b.GUEST_ID
LEFT JOIN RESTAURANT_PAYMENT AS p ON g.GUEST_ID = p.GUEST_ID
WHERE g.LEVEL IN ('Gold', 'Platinum')
GROUP BY g.NAME, g.LEVEL
ORDER BY TOTAL_SPENT DESC, GUEST_NAME ASC;


/* 오답 코드
SELECT
    g.NAME AS GUEST_NAME,
    g.LEVEL AS LEVEL,
    COUNT(b.BOOKING_ID) AS STAY_COUNT,
    COUNT(DISTINCT p.PAY_ID) AS MEAL_COUNT,
    SUM(b.ROOM_FEE + p.BASE_FEE + COALESCE(p.EXTRA_FEE, 0)) AS TOTAL_SPENT
FROM HOTEL_GUEST AS g
INNER JOIN ROOM_BOOKING AS b ON g.GUEST_ID = b.GUEST_ID
LEFT JOIN RESTAURANT_PAYMENT AS p ON g.GUEST_ID = p.GUEST_ID
WHERE g.LEVEL IN ('Gold', 'Platinum')
GROUP BY g.NAME, g.LEVEL
ORDER BY TOTAL_SPENT DESC, GUEST_NAME ASC;